version: '2'
services:

#################################################
# title:   Cakephp Web Application
# author:  Ronie Vincent Horca
# contact: <ronievincent.gss@gmail.com>
#################################################

 cakeblog:
   build: .
   ports:
     - "4000:80"
   depends_on:
     - mysql
   links:
     - mysql
   volumes:
     - ".:/var/www/html/"
   environment:
     - SECURITY_SALT=ashg4543323dd3434343434dsddet556kk
     - MYSQL_URL=mysql
     - MYSQL_USERNAME=root
     - MYSQL_PASSWORD=test
   networks:
     - cake-network
 mysql:
   image: mysql:5.7
   container_name: phpmyadmin_mysql
   volumes:
     - mysql_data:/var/lib/mysql
   environment:
     - MYSQL_ROOT_PASSWORD=test
     - MYSQL_DATABASE=cakeblog
   networks:
     - cake-network

#################################################
# phpmyadmin credentials
#################################################
# server => phpmyadmin_mysql
# user => root
# password => test
# remember to import the database tables
# to use your app

 phpmyadmin:
   image: phpmyadmin/phpmyadmin
   container_name: phpmyadmin
   links:
     - mysql:db
   depends_on: 
     - mysql
   ports:
     - "8080:80"
   environment:
     - PMA_ARBITRARY=1
     - PMA_HOST=mysql
     - PMA_PORT=3306
   networks:
     - cake-network
volumes:
   mysql_data:

networks:
   cake-network:
      driver: bridge

